"""add created_at descending index

Revision ID: 3df93d81ad92
Revises: 92e1c02d5f47
Create Date: 2026-03-24 23:11:40.325316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df93d81ad92'
down_revision: Union[str, None] = '92e1c02d5f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_qr_codes_created_at', 'qr_codes', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_qr_codes_created_at', table_name='qr_codes')
    # ### end Alembic commands ###
